### PR TITLE
Adding initial project for scraper

### PR DESCRIPTION
**Pull request by sahanaudupa**
This pulls in issues (title, Id, body, labels) and stores it in a json format

### CODE REVIEW

**Comment by devigned** [comment]
@sahanaudupa it's a best practice to not commit .dlls and other build artifacts. I noticed you didn't have a `.gitignore` file, which would have omitted the build artifacts. Adding something like [this](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) template will ensure git doesn't add those files in the future.

**Comment by sahanaudupa** [comment]
I have added .gitignore file. I didn't change the file in the template although I don't need all of those filters for now, it will be useful later with more changes.

**Comment by sahanaudupa** [comment]
I can remove /packages. I have faced issues with nuget in the past, so I added the /packages as well. I will remove them

**Comment by sahanaudupa** [comment]
Removed packages

**Pull request merged**
